maxRows=36;
var jRowsPerPage=36+1;
jTitle="VALVE LITERATURE";
jInitialSrc="IMAGES/01-00038_PR_PICV_VRN_WhitePaper.pdf";
var items = [];
var row;
row = {Id:'2',Date:'1/1/2016',Score:'',Title:'Advantages of Pressure Independet Control Valves',DocType:'PDF',Summary:'Advantages of Pressure Independent Control Valves',Path:'IMAGES/01-00038_PR_PICV_VRN_WhitePaper.pdf'};
items.push(row);
row = {Id:'3',Date:'1/2/2016',Score:'',Title:'Finite Element Analysis design of fluid-flow control nano-valve',DocType:'PDF',Summary:'Finite Element Analysis-based design of fluid-flow control nano-valve',Path:'IMAGES/10.1.1.538.9744.pdf'};
items.push(row);
row = {Id:'4',Date:'1/3/2016',Score:'',Title:'Laplace Pressure Valve',DocType:'PDF',Summary:'Laplace Pressure Valve',Path:'IMAGES/358_0381.pdf'};
items.push(row);
row = {Id:'5',Date:'1/4/2016',Score:'',Title:'Potter Roemer Angle Flow Valves',DocType:'PDF',Summary:'Potter Roemer Angle Flow Valves',Path:'IMAGES/4060.pdf'};
items.push(row);
row = {Id:'6',Date:'1/5/2016',Score:'',Title:'Solid Electrolyte Valve for Micro/Nano-fluidics',DocType:'PDF',Summary:'Solid Electrolyte Valve for Micro/Nano-fluidics',Path:'IMAGES/670.pdf'};
items.push(row);
row = {Id:'7',Date:'1/15/2015',Score:'',Title:'Nanovalves',DocType:'PDF',Summary:'Nanovalves',Path:'IMAGES/Adv.Func.Mater.2007.17.5.685.693.pdf'};
items.push(row);
row = {Id:'8',Date:'8/14/2015',Score:'',Title:'10mm Nanovalves',DocType:'PDF',Summary:'10mm Nanovalves',Path:'IMAGES/B_katalog.pdf'};
items.push(row);
row = {Id:'9',Date:'4/1/2016',Score:'',Title:'2-Way High Vacuum Ball Valves',DocType:'PDF',Summary:'BallValve2Way-DS',Path:'IMAGES/BallValve2Way-DS.pdf'};
items.push(row);
row = {Id:'10',Date:'9/1/2016',Score:'',Title:'Bellows Seal Valves (Hitachi/Gourd)',DocType:'PDF',Summary:'Bellows Seal Valves\, Ductile Iron / Stainless Steel / Forged Steel / Cast Steel',Path:'IMAGES/eca_01.pdf'};
items.push(row);
row = {Id:'11',Date:'9/12/2016',Score:'',Title:'Butterfly Valves',DocType:'PDF',Summary:'Butterfly_valves_ENG',Path:'IMAGES/Butterfly_valves_ENG.pdf'};
items.push(row);
row = {Id:'12',Date:'9/12/2016',Score:'',Title:'Parker Angle Body Valves',DocType:'PDF',Summary:'CIC_FCD_AngleBodyValve-Brochure',Path:'IMAGES/CIC_FCD_AngleBodyValve-Brochure.pdf'};
items.push(row);
row = {Id:'13',Date:'9/12/2016',Score:'',Title:'Nano/Micro aerosol particles measurement for UHV slit valves',DocType:'PDF',Summary:'Nano/Micro aerosol particles measurement for the UHV slit valves',Path:'IMAGES/CMEM060313f.pdf'};
items.push(row);
row = {Id:'14',Date:'9/14/2016',Score:'',Title:'Consider Moving to Fixed Valves',DocType:'PDF',Summary:'Consider-moving-to-fixed-valves',Path:'IMAGES/Consider-moving-to-fixed-valves.pdf'};
items.push(row);
row = {Id:'15',Date:'9/20/2016',Score:'',Title:'Damage Scenarios for Valves',DocType:'PDF',Summary:'Damage_scenarios_for_valves',Path:'IMAGES/Damage_scenarios_for_valves.pdf'};
items.push(row);
row = {Id:'16',Date:'9/20/2016',Score:'',Title:'Flanged Valves - 2017 Catalog',DocType:'PDF',Summary:'Flanged-2017-catalog',Path:'IMAGES/Flanged-2017-catalog.pdf'};
items.push(row);
row = {Id:'17',Date:'9/20/2016',Score:'',Title:'Flowrox Valve Solutions Catalog 9.2018 e-version',DocType:'PDF',Summary:'Flowrox_Valve_Solutions_Catalogue_20.9.2018_e-version',Path:'IMAGES/Flowrox_Valve_Solutions_Catalogue_20.9.2018_e-version.pdf'};
items.push(row);
row = {Id:'18',Date:'9/20/2016',Score:'',Title:'Ion Channel Nanovalves',DocType:'PDF',Summary:'Ion Channel Nanovalves',Path:'IMAGES/Ion Channel Nanovalves.pdf'};
items.push(row);
row = {Id:'19',Date:'9/23/2016',Score:'',Title:'JACS Molecular Nanovalves',DocType:'PDF',Summary:'JACS Molecular Nanovalves',Path:'IMAGES/JACS Molecular Nanovalves.pdf'};
items.push(row);
row = {Id:'20',Date:'9/23/2016',Score:'',Title:'Multipurpose Ball Valves',DocType:'PDF',Summary:'Multipurpose Ball Valves',Path:'IMAGES/MS-02-345.PDF'};
items.push(row);
row = {Id:'21',Date:'12/15/2016',Score:'',Title:'Mesoporous Silica Nanovalves',DocType:'PDF',Summary:'Mesoporous Silica Nanovalves',Path:'IMAGES/Mesoporous Silica Nanovalves.pdf'};
items.push(row);
row = {Id:'22',Date:'3/7/2017',Score:'',Title:'Nano Laplace Valve',DocType:'PDF',Summary:'Nano Laplace Valve',Path:'IMAGES/Nano Laplace Valve.pdf'};
items.push(row);
row = {Id:'23',Date:'4/1/2017',Score:'',Title:'Farewell to the Medtronic Hall Valve',DocType:'PDF',Summary:'Farewell to the Medtronic Hall Valve',Path:'IMAGES/PIIS002252231500118X.pdf'};
items.push(row);
row = {Id:'24',Date:'5/22/2017',Score:'',Title:'Poppets-vs-Spool Valves',DocType:'PDF',Summary:'Poppets-vs-Spool-Valves',Path:'IMAGES/Poppets-vs-Spool-Valves.pdf'};
items.push(row);
row = {Id:'25',Date:'5/26/2017',Score:'',Title:'Reprocessing of Endoscopic Accessories and Valves',DocType:'PDF',Summary:'Reprocessingvalvesdocument_FINAL',Path:'IMAGES/Reprocessingvalvesdocument_FINAL.pdf'};
items.push(row);
row = {Id:'26',Date:'6/13/2017',Score:'',Title:'Rheodyne MX HPLC Solutions Guide',DocType:'PDF',Summary:'Rheodyne_MX_Solutions_Guide',Path:'IMAGES/Rheodyne_MX_Solutions_Guide.pdf'};
items.push(row);
row = {Id:'27',Date:'6/23/2017',Score:'',Title:'Valve - New Employee Handbook',DocType:'PDF',Summary:'Valve_NewEmployeeHandbook',Path:'IMAGES/Valve_NewEmployeeHandbook.pdf'};
items.push(row);
row = {Id:'28',Date:'6/23/2017',Score:'',Title:'Shape Optimization of Micropump Fixed Valves',DocType:'PDF',Summary:'Improvement in fixed-valve micropump performance through shape optimization of valves',Path:'IMAGES/gamboa05a.pdf'};
items.push(row);
row = {Id:'29',Date:'6/26/2017',Score:'',Title:'New Piezoelectric Valve',DocType:'PDF',Summary:'New piezoelectric valve',Path:'IMAGES/hannover 172.pdf'};
items.push(row);
row = {Id:'30',Date:'6/26/2017',Score:'',Title:'Rheodyne High Pressure Valves',DocType:'PDF',Summary:'Rheodyne High Pressure Valves',Path:'IMAGES/idexhs_catalog_valves.pdf'};
items.push(row);
row = {Id:'31',Date:'8/31/2017',Score:'',Title:'Parasites and Pathologies of Bivalves',DocType:'PDF',Summary:'A systematic review of the parasites and pathologies of the main important commercially bivalve species from Argentina and Uruguay',Path:'IMAGES/review-of-parasites-and-pathologies-of-the-main-bivalve-species-of-commercial-interest-of-argentina-and-uruguay-southwestern-atlan.pdf'};
items.push(row);
row = {Id:'32',Date:'9/27/2017',Score:'',Title:'Stimuli-Response DNA Nanovalves',DocType:'PDF',Summary:'Stimuli-response DNA Nanovalves',Path:'IMAGES/nanoBioMed2013.pdf'};
items.push(row);
row = {Id:'33',Date:'9/28/2017',Score:'',Title:'Molecular Machines Drive Smart Drug Delivery',DocType:'PDF',Summary:'Molecular machines drive smart drug delivery',Path:'IMAGES/nnm.10.111.pdf'};
items.push(row);
row = {Id:'34',Date:'12/20/2017',Score:'',Title:'MX Series II Automated Valve Modules (HPLC)',DocType:'PDF',Summary:'MX Series II Automated Valve Modules',Path:'IMAGES/rheodynemxiivalves.pdf'};
items.push(row);
row = {Id:'35',Date:'1/8/2018',Score:'',Title:'Saunders Industrial Diaphragm Valves',DocType:'PDF',Summary:'saunders-industrial-diaphragm-valves',Path:'IMAGES/saunders-industrial-diaphragm-valves.pdf'};
items.push(row);
row = {Id:'36',Date:'1/21/2018',Score:'',Title:'Selecting HVAC Control Valves -Ball-vs-Globe',DocType:'PDF',Summary:'selecting-control-valves-ball-vs-globe',Path:'IMAGES/selecting-control-valves-ball-vs-globe.pdf'};
items.push(row);
